### PR TITLE
Draft: neofetch boot configurable by motd.txt

### PR DESCRIPTION
**Pull request by adiee5**
This pull request adds a functionality to startup routine, that executes neofetch external command in case the first line of motd.txt is equal to `#!neofetch`

This functionality could potentially be expanded to allow auto-starting any kind of command and other things.

### CODE REVIEW

**Comment by irmen** [comment]
interesting idea

**Comment by adiee5** [comment]
But ok, if we are going to implement this thing, we need to plan everything out:

1. are we going to continue using *modt.txt* for now, or we'll implement *shell.rc* from the beginning?
2. are we going to work from my current commits or should we start form scratch again?
3. if we implement *shell.rc*, should we make a separate folder for config files maybe, or are we going to place everything into `SHELL-CMDS` as it is now? (i think we will need to make subfolders of `SHELL-CMDS` sooner or later - I already had an idea of a `lib` folder while back ago for hypothetical more complex command-line software, that'd need external libraries)
4. are we going to allow everything or maybe only selected commands for safety (I guess the answer's everything, based on what you said)
5. If we go *shell.rc* route, should it be just for executing commands on boot or should it also be a config file? If so, how are we going to differentiate between a config option and a command?
6. If *shell.rc* route, what if user doesn't have the *shell.rc*? Will `SHELL.PRG` create a default config, crash, or run some kind of default routine completely ambiguous to end user?
7. Multiple commands in shell.rc? (probably yes)
8. is Motd on boot going to be configured in *shell.rc* or will it run regardless of what *shell.rc* says?

and there are probably many more questions, that we should answer, but i didn't think about

**Comment by irmen** [comment]
I will think about all of those valid questions later today, but can tell you now that I want the motd.txt to be just that - a text file. No magic stuff in it. So everything else will go into a separate file :)

**Comment by adiee5** [comment]
This is done by 5e2dffa

**Pull request closed without merging**
